name: 'Resources Deployment'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  agent-setup:
    name: 'Agent setup'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Terraform 1.5.7
      run: ${GITHUB_WORKSPACE}/install-terraform.sh

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
  execute-terraform:
    name: 'Execute Terraform'
    runs-on: ubuntu-latest
    needs: agent-setup
    environment: production

    defaults:
      run:
        shell: bash
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Terraform init
      run: ${GITHUB_WORKSPACE}/execute-terraform.sh -a init -e main

    - name: Terraform plan
      run: ${GITHUB_WORKSPACE}/execute-terraform.sh -a plan -s key_vault -e main

    - name: Terraform apply
      run: ${GITHUB_WORKSPACE}/execute-terraform.sh -a apply  -s key_vault -e main