name: 'Resources Deployment'

on: workflow_dispatch

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  execute-terraform:
    name: 'Execute Terraform'
    runs-on: ubuntu-latest
    environment: main

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Terraform 1.5.7
      run: ${GITHUB_WORKSPACE}/install-terraform.sh

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Whitelist GitHub Runner IP
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          agentIP=$(curl -s https://api.ipify.org/)
          az storage account network-rule add \
            --resource-group "${{ secrets.RESOURCE_GROUP }}" \
            --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --ip-address $agentIP
          sleep 30
      
    - name: Key Vault Creation
      run: |
        ${GITHUB_WORKSPACE}/execute-terraform.sh -a init -s key_vault -e main
        ${GITHUB_WORKSPACE}/execute-terraform.sh -a plan -s key_vault -e main
        ${GITHUB_WORKSPACE}/execute-terraform.sh -a apply -s key_vault -e main

    - name: App Service Creation
      run: |
        ${GITHUB_WORKSPACE}/execute-terraform.sh -a init -s app_service -e main
        ${GITHUB_WORKSPACE}/execute-terraform.sh -a plan -s app_service -e main
        ${GITHUB_WORKSPACE}/execute-terraform.sh -a apply -s app_service -e main

    - name: Remove GitHub Runner IP from Whitelist
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          agentIP=$(curl -s https://api.ipify.org/)
          az storage account network-rule remove  \
            --resource-group "${{ secrets.RESOURCE_GROUP }}" \
            --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --ip-address $agentIP